### ISSUE TITLE
incorrect tag sem version

### ISSUE THREAD

**Issue by sergolius** [gabriel-vasile/mimetype#196]
1. `v1.1.2` changed behaviour of `mimetype.Detect`. (With `v1.1.1` client could read data till second `\n`, to have two lines of CSV, to solve https://github.com/gabriel-vasile/mimetype/issues/138)
2. `v1.3.0` Go 1.17 minimum is required for dependency `golang.org/x/net`.

**Comment by gabriel-vasile** [comment]
Hi
1. please provide a minimal test-case showing expected behavior and what actually happens.
2. Should I update go.mod to from 1.12 to 1.17? Do you have a reference for why this should be done or explain a situation where it was an issue?
I always assumed `go mod tidy` does everything that needs to be done for go.mod and go.sum.
