### ISSUE TITLE
Bad mime type for python scripts?

### ISSUE THREAD

**Issue by NDagestad** [gabriel-vasile/mimetype#284]
Hi, the mime type of python scripts is returned as **application/x-python** but this seems to be rather unique to this library.
The `file` command list python scripts as **text/x-script.python** and python itself uses **text/x-python**. There doesn't seem to be any official mime type for them so I guess any choice is equally valid but I feel like the last one would be the better (though one could argue that giving the same result as `file` is also a good choice).

I didn't see any justification for using **application/x-python** in the pull request adding  it #10, and the and in the issue #1 about missing mime-types, **text/x-python** was referenced multiple times and seemed to be the the preferred one. Is there a reason I am missing for why **application/x-python** was chosen in the end ?

Also the [RFC 6838](https://datatracker.ietf.org/doc/html/rfc6838#section-4.2.5) for mime types says application/* is for medias that do not fit under on one of the other. The second paragraph in that section explains that some content that is technically plain text code uses the application type, like javascript, but mostly because it is not intended to be viewed by the user but simply transferred and executed immediately, I would argue that python does not usually fall in that category.

**Comment by gabriel-vasile** [comment]
Hi, `application/x-python` was initially chosen because the detection works for [python scripts](https://github.com/gabriel-vasile/mimetype/blob/14adc293c7505feb4cb250a5b78469723bb1e85f/testdata/py.py) that are meant to be run in command line.

But you are right, we should use `text/x-python` because that's what python itself chose.
I will go ahead and make `text/x-python` the main mime type and  `text/x-script.python` and `application/x-python` as aliases.

**Comment by jesselang** [comment]
Looks like this can be closed?

**Comment by NDagestad** [comment]
Yes, could probably have been closed over a year ago, thank you
