### ISSUE TITLE
.torrent file in testdata  getting detected as malicious file and causing build issue. 

### ISSUE THREAD

**Issue by Amit99Shah** [gabriel-vasile/mimetype#398]

**Comment by gabriel-vasile** [comment]
@Amit99Shah what's the name of the tool that reports .torrent as malicious?

**Comment by gabriel-vasile** [comment]
.torrent files are not inherently malicious; the [testdata torrent.torrent](https://github.com/gabriel-vasile/mimetype/blob/c9ecfddbcc8324b58390f54d4f57e35ad67a60de/testdata/torrent.torrent) is just downloading an Arch linux iso.

I will gladly fix this problem if the tool that you are using did some thoroughly  checks and found malicious intent inside that file. But if it only looked at the extension and deemed it malicious, then I don't think there's anything to fix.

**Comment by FurmanovD** [comment]
@gabriel-vasile it's a common practice to avoid any potential legal issues.
I also faced this issue because playground/validator has got a dependency on your module.
And I was forced to just downgrade the validator.

**Comment by gabriel-vasile** [comment]
To me, this seems a gross approach from FortiClient. 
That being said, I understand how this argument can drag for too long so I'm willing to take steps forward once the problem is clear.

@FurmanovD, @Amit99Shah and anyone else having similar problems, your answers are greatly appreciated.

1. Is it only `.torrent` that causes problems?
2. Does renaming the file `.torrent` -> `.nottorrent` silence those "security" tools?
3. If answer to 2. was no, does encoding the file (zip, base64, etc.) fix the error?
4. What exactly is the reported problem? Is it security or legal related?
