### ISSUE TITLE
Fix package structure

### ISSUE THREAD

**Issue by arngrimur** [gabriel-vasile/mimetype#469]
Today when importing`mimetype` using `go mod vendor` some unnecessary files ar e included since they are in the same package as the go files

By moving `mime.go`, `mimetypes.go` and `tree.go` to folder `pkg` it is possible to reduce the size of vendored files by almost 1.5M. It is not a lot but if applications vendoring lots of libs they accumulate

Thanks! 

P:S I can  do the work and send  a PR if you want

**Comment by gabriel-vasile** [comment]
1.3 out of 1.5M are because of `mimetype.gif` inside root directory. [Let me move that file to `testdata` folder and reduce by 1.3M.](https://github.com/gabriel-vasile/mimetype/pull/548)
There are still 0.2M coming from various text files inside root directory, but I would like not to change project structure.

```bash
go get -u github.com/gabriel-vasile/mimetype@master
go mod  vendor
```
Should show a smaller dir size now.
