### ISSUE TITLE
Why Kaspersky AV flagging the module test data 

### ISSUE THREAD

**Issue by abhisekp** [gabriel-vasile/mimetype#575]
Check the image below.

![image](https://github.com/user-attachments/assets/23aee442-7cef-4721-8d3d-cf346a6302ef)

**Comment by mk26710** [comment]
Seems like this is a tar bomb and it was removed from the repo some time earlier in this commit - https://github.com/gabriel-vasile/mimetype/commit/32671160da7a800a2765472b24ea4c050fa728f5

This is really weird to have such thing in a repo actually ngl, I didn't even download this package myself since it was a dependency of another package. Anyway, I hope there are no more funny files like that in tests, the moment my AV detected this in a test file I remembered about that XZ vulnerability thinking maybe it's the same situation here, but thankfully it seems to not to be the case. Well, hopefully. would really like to read maintainer's comments on this one.

**Comment by gabriel-vasile** [comment]
I added the file in #466 as a test case. I had no malicious intentions.
To be clear on the consequences of messing with that tarbomb: it will simply extract a file until all disk space is used. It will **not** overwrite any files on the host.

Before the commit:
I extracted the file and my archiver detected it's a tar bomb and protected me by extracting just one file. 
I then concluded that archiving software is smart nowadays and not falling for this kind of traps (it probably is, but antiviruses take the side of caution.)
TBH, antivirus software was never in my mind all that time.

After the commit:
I released [v1.4.5](https://github.com/gabriel-vasile/mimetype/releases/tag/v1.4.5) which does not contain the tarbomb.
[`testdata/exe` file was reported as virus by different software](https://github.com/gabriel-vasile/mimetype/issues/550). [Removed as well in v1.4.5.](https://github.com/gabriel-vasile/mimetype/pull/561)


Going forward, I will retract v1.4.4 on next release and remove the testdata files and replace them with classic golang unit tests.
Using the `testdata` directory was probably a mistake. I did it because some file formats are complicated and storing as files, instead of byte slices in golang, was easy.


How to fix the issue on your side: upgrade to v1.4.5 if you have the option, otherwise... not much can be done. Maybe just ask the antivirus to quarantine the file.
