### ISSUE TITLE
.xlsx incorrectly detect as .zip

### ISSUE THREAD

**Issue by katticot** [gabriel-vasile/mimetype#81]
[test.xlsx](https://github.com/gabriel-vasile/mimetype/files/4041595/test.xlsx)
**Attach the file for which the detection is inaccurate**
You can use the file sharing site of your choice, just ensure the file will not expire or get deleted.

**Expected mime
 xlsx

**Returned mime 
zip

**Version of the library you are using**
the semver version or the hash of the commit
1fe33ab3a6ac95640b54547b3b9a38fb5351de10

**Output of `go version`**
go 1.13

**Comment by katticot** [comment]
Hi @gabriel-vasile ,

Thx a lot for the fix.
To generate  xlsx i use Excel 2013 (15.0.5189.1000) 32 bits

**Comment by cll0ud** [comment]
Hi everyone.

I had the same problem with a .xlsx downloaded from Google Sheets, the output is `application/zip`.

**Comment by gabriel-vasile** [comment]
Hi!xlsx files are

**Comment by gabriel-vasile** [comment]
Hi!
xlsx documents are just zip archives with some specific files inside them. The zip format does not care about the order of the files inside the archive and sometimes, the files `mimetype` uses to detect the format end up in the end of the archive. This is an issue because `mimetype` reads only the first [3072](https://github.com/gabriel-vasile/mimetype/blob/master/internal/matchers/matchers.go#L4) bytes from a file. 

The solutions  I see are:
1) increase ReadLimit or maybe add a function for clients to set it.
2) maybe find some other files which can be used to identify the format.

First I will try option 2) because it brings no changes to the library API. Will update here the progress.

**Comment by gabriel-vasile** [comment]
Hi @cll0ud,
before I merge these new changes, can you please run
```bash
go get github.com/gabriel-vasile/mimetype@3b3626c6
``` 
and confirm the detection is correct now?

**Comment by cll0ud** [comment]
Hi @gabriel-vasile. It's working, thank you!
