### ISSUE TITLE
Create a MIME type based on its name

### ISSUE THREAD

**Issue by JonasDoe** [gabriel-vasile/mimetype#98]
I have a (generated) whitelist of allowed MIME types and want to check whether an incoming MIME type is allowed, but apparently it's not possible to create a list of MIME types with some kind of factory like `mimetype.Of("image/jpeg")`. There's only an indirect way to access an existing, well-known MIME type via `mimetype.DetectFile()`, but it seems a bit odd to create pseudo files just to get the proper MIME type, and in my case its not even feasible.
Some support to access known MIME types (in `tree.go`) would be great!

**Comment by gabriel-vasile** [comment]
Hi,
Giving access to the list of known MIME types would limit users to only the registered ones. 
On the other hand, adding a function to instantiate a `*MIME`, so it can later be checked against a list is a little too complicated. More than that, `mimetype.Of` needs to receive info about file extension and maybe MIME aliases, in order to make the new MIME as usable as the registered ones.

However, I think a function like `mimetype.Equal(m1, m2 string) bool` would help your case.

**Comment by JonasDoe** [comment]
Hi,
thanks for your fast response! The only disadvantage of a method like `mimetype.Equal(m1, m2 string) bool` which comes to my mind is that the comparison might a bit slower than with a prepared MIME type at hand. But that's probably neglectable.

**Comment by gabriel-vasile** [comment]
Oh, `Of` makes better sense now but it still has it's limitation.

The cost of `Equal` is 2 X time required to [parse](https://godoc.org/mime#ParseMediaType) a MIME type. 
A faster approach when testing a MIME type against a whitelist would be a function like `EqualsAny(search string, mimes ...string) bool`. It returns true if `search` is equal to any of `mimes`. For a whitelist of length n,`EqualsAny` would require n+1 parsings, compared to 2n of `Equal`. 

Right now, I'm leaning towards `EqualsAny` for the performance and because it saved users from writing the loop.
Any suggestions for a name for `EqualsAny`? Or maybe disadvantages it has compared to others?

**Comment by gabriel-vasile** [comment]
Hi,
[mimetype.EqualsAny()](https://godoc.org/github.com/gabriel-vasile/mimetype#EqualsAny) is availale in v1.1.0.

**Comment by JonasDoe** [comment]
That was fast! Thank you!
